name: Gerar CHANGELOG do README

on:
  push:
    paths:
      - "README.md"
    paths-ignore:
      - "CHANGELOG.md"   # evita loop se o workflow commitar CHANGELOG.md

jobs:
  changelog:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout do repositório
        uses: actions/checkout@v4
        with:
          fetch-depth: 0       # permite usar git log corretamente

      - name: Criar/atualizar CHANGELOG.md
        run: |
          printf "## %s - Alteração no README\n\n- Commit: %s\n- Autor: %s\n- Mensagem: %s\n\n" \
            "$(date -u +"%Y-%m-%d %H:%M:%SZ")" "$GITHUB_SHA" "$GITHUB_ACTOR" "$(git log -1 --pretty=%B)" \
            >> CHANGELOG.md

      - name: Configurar Git
        run: |
          git config user.name "github-actions[bot]"
          git config user.email "github-actions[bot]@users.noreply.github.com"

      - name: Commitar e dar push (só se houver mudanças)
        run: |
          git add CHANGELOG.md
          # se não houver mudanças staged, git diff --cached --quiet retorna 0
          if git diff --cached --quiet; then
            echo "Sem alterações para commitar"
          else
            git commit -m "Atualização automática do CHANGELOG (README editado)"
            git push
          fi
        env:
          # GITHUB_TOKEN já está disponível automaticamente; mantido aqui por clareza
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
