name: Gerar CHANGELOG do README

on:
  push:
    paths:
      - "README.md"

jobs:
  changelog:
    runs-on: ubuntu-latest
    if: github.actor != 'github-actions[bot]'  # evita loop

    steps:
      - name: Checkout do repositório
        uses: actions/checkout@v4
        with:
          fetch-depth: 0

      - name: Criar/atualizar CHANGELOG.md
        run: |
          printf "## %s - Alteração no README\n\n- Commit: %s\n- Autor: %s\n- Mensagem: %s\n\n" \
            "$(date -u +"%Y-%m-%d %H:%M:%SZ")" "$GITHUB_SHA" "$GITHUB_ACTOR" "$(git log -1 --pretty=%B)" \
            >> CHANGELOG.md

      - name: Configurar Git
        run: |
          git config user.name "github-actions[bot]"
          git config user.email "github-actions[bot]@users.noreply.github.com"

      - name: Commitar e dar push (só se houver mudanças)
        run: |
          git add CHANGELOG.md
          if git diff --cached --quiet; then
            echo "Sem alterações para commitar"
          else
            git commit -m "Atualização automática do CHANGELOG (README editado)"
            git push https://x-access-token:${{ secrets.GITHUB_TOKEN }}@github.com/${{ github.repository }}.git HEAD:${{ github.ref_name }}
          fi
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
